apiVersion: v1
kind: Secret
metadata:
  name: {{ include "thingtype.fullname" . }}
  labels:
    {{- include "thingtype.labels" . | nindent 4 }}
type: Opaque
data:
  PASSWORD: {{ .Values.secret.password | b64enc | quote }}
  DB_USER: {{ .Values.secret.username | b64enc | quote }}
  DB_URL: {{ .Values.secret.url | b64enc | quote }}