apiVersion: v1
kind: PersistentVolume
metadata:
  name: couch-pv-volume
  labels:
    type: local
spec:
  storageClassName: my-local-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/data/couchdb"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-master