apiVersion: v1
kind: Service
metadata:
  name: couch-couchdb
  labels:
    app: couchdb
spec:
  type: LoadBalancer
  ports:
    - port: 5984
      targetPort: 5984
      protocol: TCP
      name: http

  selector:
    app: couchdb