apiVersion: v1
kind: Service
metadata:
  name: couch-couchdb
  labels:
    app: couchdb
spec:
  type: LoadBalancer
  ports:
    - port: 5984
      targetPort: 5984
      protocol: TCP
      name: http

  selector:
    app: couchdb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: couchdb-set
spec:
  serviceName: couchdb
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
          app: couchdb
    spec:
      containers:
      - name: couchdb
        image: couchdb:3.3.2
        env:
        - name: COUCHDB_USER
          value: admin
        - name: COUCHDB_PASSWORD
          value: INWJyexD
        ports:
        - name: http
          containerPort: 5984
        volumeMounts:
        - name: couchdb-vol
          mountPath: /opt/couchdb/data
        
  volumeClaimTemplates:
  - metadata:
      name: couchdb-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
          requests:
            storage: 2G
      